export const ADD_INGREDIANT = 'ADD_INGREDIANT';
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const FETCH_INGREDIANTS = 'FETCH_INGREDIANTS'
export const ERROR_FETCH = 'ERROR_FETCH'

// order actions
export const POST_ORDER = 'POST_ORDER'
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL'
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS'
export const PURCHASING_BURGER_START = 'PURCHASING_BURGER_START'
export const PURCHASED = 'PURCHASED'
export const GET_ORDERS_FROM_DATABASE = 'GET_ORDERS_FROM_DATABASE'
export const EMPTY_ORDERS_STATE = 'EMPTY_ORDERS_STATE'
export const CHANGE_IS_USER_ORDER_FETCHED = 'CHANGE_IS_USER_ORDER_FETCHED'

//Auth actions
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
